version: '3.9'

services:
  server:
    build: ./med-spot-api
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: 'postgres'
    ports:
      - '4321:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: